### ISSUE TITLE
Recording audio/video calls

### ISSUE THREAD

**Issue by bharat-patidar** [Terrance/SkPy#104] opened 2019-01-26 21:25 UTC
Can we expect any functionality to record meeting(audio/video) through this code. If No, Can you please suggest any source from where I can get the same.

Thank You

**Comment by Terrance** [comment] 2019-01-26 21:54
Duplicate of #55 -- calls use a propriatary plugin, and I don't know of anything else that reimplements it.

**Closed by Terrance** 2019-01-26 21:54 UTC
Labels: duplicate
