### ISSUE TITLE
'Account action required (https://account.live.com/identity/confirm), login with a web browser first', <Response [200]>

### ISSUE THREAD

**Issue by researcher26** [Terrance/SkPy#166] opened 2021-01-29 11:40 UTC
When i tried to login by 

`sk=Skype(login, pwd)`

i catch the Exception

'Account action required (https://account.live.com/identity/confirm), login with a web browser first', <Response [200]>

May be somebody solve the problem? Give me advice please

**Comment by Terrance** [comment] 2021-01-29 13:19
The exception tells you what you need to do.  Failing that, duplicate of #145.

**Closed** 2021-01-29 13:19 UTC
Labels: duplicate, question
