### ISSUE TITLE
Can use this to make a phone call from skype

### ISSUE THREAD

**Issue by sadazs** [Terrance/SkPy#138] opened 2020-08-16 07:09 UTC
Hi I need help
Can use this script to make a phone call from skype

**Comment by Terrance** [comment] 2020-08-16 16:07
Duplicate of #55 -- whilst WebRTC is more standardised than the plugin they used to require, SkPy still only intends to cover the basic HTTP APIs for messaging, not calls.

**Closed by Terrance** 2020-08-16 16:07 UTC
Labels: duplicate
