### ISSUE TITLE
No token file specified

### ISSUE THREAD

**Issue by nilpatel62** [Terrance/SkPy#101] opened 2018-12-01 06:42 UTC
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/skpy/main.py", line 67, in __init__
    self.conn.readToken()
  File "/usr/lib/python3.5/site-packages/skpy/conn.py", line 288, in readToken
    raise SkypeAuthException("No token file specified")
skpy.core.SkypeAuthException: No token file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trello.py", line 3, in <module>
    sk = Skype('nilpatel62@gmail.com', 'neel1368') # connect to Skype
  File "/usr/lib/python3.5/site-packages/skpy/main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "/usr/lib/python3.5/site-packages/skpy/conn.py", line 266, in getSkypeToken
    self.liveLogin(user, pwd)
  File "/usr/lib/python3.5/site-packages/skpy/conn.py", line 368, in liveLogin
    self.tokens["skype"], self.tokenExpiry["skype"] = SkypeLiveAuthProvider(self).auth(user, pwd)
  File "/usr/lib/python3.5/site-packages/skpy/conn.py", line 542, in auth
    t = self.sendCreds(user, pwd, params)
  File "/usr/lib/python3.5/site-packages/skpy/conn.py", line 575, in sendCreds
    raise SkypeAuthException(errMsg, loginResp)
skpy.core.SkypeAuthException: ("Couldn't retrieve t field from login response", <Response [200]>)

**Comment by nilpatel62** [comment] 2018-12-01 06:44
If i'm perform the operation on localhost it will work fine but whenever i will try on server it will show me that error

**Comment by Terrance** [comment] 2018-12-01 08:14
Duplicate of #65.

**Closed** 2018-12-01 08:15 UTC
Labels: duplicate

**Comment by nilpatel62** [comment] 2018-12-01 10:53
how can i solve that problem?

**Comment by nilpatel62** [comment] 2018-12-01 10:54
but i have still have that problem how can i solve that?

**Comment by muskxn25** [comment] 2023-05-26 05:31
Authentication failed: No username or password provided, and no valid token file

Please can you help me solve this error I am running this in my server it works fine everywhere else but doesn't work on my server

**Comment by jpruiz114** [comment] 2024-02-08 19:09
I am having the same issue.
